// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxjjijuvsmvussgjyowk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4amppanV2c212dXNzZ2p5b3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTAxNTYsImV4cCI6MjA2MTU2NjE1Nn0.2mcgQD78JBAduFJvoZaqYZ30frj5MU8jiVk8AJL_01c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);